export const LOBBY_EVENTS = {
  SERVER_NEW_MESSAGE: 'SERVER_NEW_MESSAGE',
  CLIENT_SENT_MESSAGE: 'CLIENT_SENT_MESSAGE',
}

export const GAME_EVENTS = {
  FLIP_CARD: 'FLIP_CARD',
  TILEMAP_UPDATED: 'TILEMAP_UPDATED'
}