export const LOBBY_EVENTS = {
  SERVER_NEW_MESSAGE: 'SERVER_NEW_MESSAGE',
  CLIENT_SENT_MESSAGE: 'CLIENT_SENT_MESSAGE',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT'
}

export const GAME_EVENTS = {
  START_GAME: 'START_GAME',
  START_ROUND: 'START_ROUND',
  FLIP_CARD: 'FLIP_CARD',
  TILEMAP_UPDATED: 'TILEMAP_UPDATED',
  END_ROUND: 'END_ROUND',
  END_GAME: 'END_GAME'
}